version: '3.8'

services:
  app:
    # GitHub Actions가 빌드해서 올릴 도커 이미지 경로
    image: asia-northeast3-docker.pkg.dev/project-4c111968-8a40-4fc9-b55/tikkle-repo/tikkle-be:latest
    container_name: tikkle-be
    ports:
      - "8080:8080"
    # 서버에 생성될 .env 파일의 환경 변수를 읽어옴
    env_file:
      - .env
    restart: unless-stopped