package com.tikkle.payment.dto.response;

public enum PaymentActionType {
    ORDER_REQUESTED,
    WAITING_APPROVAL,
    IGNORE_DUPLICATE,
    IGNORE_CARD_MISMATCH,
    IGNORE_NO_SPARE_CHANGE,
    IGNORE_CLASSIFICATION_FAILED,
    IGNORE_MINIMUM_AMOUNT_UNMET,
    UPBIT_ORDER_FAILED
}